### PR TITLE
Update config.example.js

### PR DESCRIPTION
**Pull request by AlekM15**

### CODE REVIEW

**Comment by bikegriffith** [comment]
@AlekM15 please leave those config values in your version of the app. I won't be merging them here.

**Comment by AlekM15** [comment]
I apologize for this, I did not mean to do whatever I did. I am just trying to figure out how to use your custom Boxcast portal template instead of the default boxcast embedded on my website. I am very primitive when it comes to coding and was just exploring to try and figure out how to do this. Is this something you could help me with?

[cid:1108e990-b97e-4a68-bc29-2fc1504d80a3]
________________________________

**Comment by bikegriffith** [comment]
@AlekM15 All good! I'd definitely like to help if possible, but there might be a lot to unpack if you're very new to development. I'd encourage to you search for "intro to vue.js development" tutorials and see if you understand the basics of using the Vue CLI to run a project locally, and then start to figure out how you could build your project (hint: `npm run build`) and take those files and host them on some web server.  If you can do that, then cloning/forking this project and making it work with your BoxCast account might make more sense.  Does that help point you in the right direction, or are you still confused?

**Comment by AlekM15** [comment]
Very much appreciate your reply. It's got my interest already so I'll definitely go look into vue.js and see if I can make progress in my understanding. If I don't catch on is this something we could contract Boxcast to do for us?

[cid:25a6446a-a6dc-4d93-9523-dc6950f9ac80]
________________________________

**Comment by bikegriffith** [comment]
Good luck! It's a fun tool once you get the hang of it.

At this point, we don't offer custom development like this, but we're all about improving our open source examples.  Once you figure it out (or hit some block), I'd love feedback on where we could improve the documentation!

**Pull request closed without merging**
